spring:
  cloud:
    gateway:
      routes:
        - id: test
          url: "http://localhost/api"
          predicates:
            - Path =/**
          filters:
            - AddRequestHeader=X-G_HEADER, red